export interface Scenario {
  id: string;
  name: string;
  brand: string;
  icon: string;
  desc: string;
  category: string;
  color: string;
  type: string;
}

export interface Category {
  id: string;
  label: string;
  icon: string;
}

export type FlowSteps = Record<string, string[]>;

export const SCENARIOS: Scenario[] = [
  {
    id: "grabpay-wallet",
    name: "GrabPay Wallet",
    brand: "GrabPay",
    icon: "🟢",
    desc: "E-wallet one-tap payment",
    category: "digital",
    color: "#00B14F",
    type: "wallet",
  },
  {
    id: "apple-pay-bio",
    name: "Apple Pay + Face ID",
    brand: "Apple",
    icon: "🍎",
    desc: "Biometric auth flow",
    category: "digital",
    color: "#1C1C1E",
    type: "biometric",
  },
  {
    id: "google-pay-card",
    name: "Google Pay",
    brand: "Google",
    icon: "🔵",
    desc: "Card-on-file payment",
    category: "digital",
    color: "#4285F4",
    type: "card",
  },
  {
    id: "visa-card",
    name: "Visa Credit Card",
    brand: "Visa",
    icon: "💳",
    desc: "Manual card entry + 3DS",
    category: "card",
    color: "#1A1F71",
    type: "card",
  },
  {
    id: "airbnb-booking",
    name: "Airbnb Booking",
    brand: "Airbnb",
    icon: "🏡",
    desc: "Travel booking flow",
    category: "booking",
    color: "#FF385C",
    type: "card",
  },
  {
    id: "agoda-booking",
    name: "Agoda Booking",
    brand: "Agoda",
    icon: "🏨",
    desc: "Hotel booking · Online Banking",
    category: "booking",
    color: "#E31837",
    type: "bank",
  },
  {
    id: "klook-booking",
    name: "Klook Booking",
    brand: "Klook",
    icon: "🎟️",
    desc: "Activity booking · Card & Atome",
    category: "paylater",
    color: "#FF5722",
    type: "paylater",
  },
  {
    id: "grabpoints",
    name: "GrabRewards Points",
    brand: "GrabPay",
    icon: "⭐",
    desc: "Pay with loyalty points",
    category: "points",
    color: "#00B14F",
    type: "points",
  },
  {
    id: "shopee-coupon",
    name: "Shopee + Voucher",
    brand: "Shopee",
    icon: "🛍️",
    desc: "Coupon & credits checkout",
    category: "rewards",
    color: "#EE4D2D",
    type: "wallet",
  },
  {
    id: "amazon-1click",
    name: "Amazon 1-Click",
    brand: "Amazon",
    icon: "📦",
    desc: "Instant purchase flow",
    category: "digital",
    color: "#FF9900",
    type: "card",
  },
  {
    id: "pending-bank",
    name: "Pending Transaction",
    brand: "Bank Transfer",
    icon: "⏳",
    desc: "FPX / bank transfer",
    category: "edge",
    color: "#D97706",
    type: "bank",
  },
  {
    id: "failed-decline",
    name: "Card Declined",
    brand: "Visa",
    icon: "❌",
    desc: "Insufficient funds error",
    category: "edge",
    color: "#E11D48",
    type: "card",
  },
  {
    id: "offline-error",
    name: "Network Failure",
    brand: "System",
    icon: "📶",
    desc: "Connectivity loss mid-pay",
    category: "edge",
    color: "#64748B",
    type: "error",
  },
  {
    id: "agoda-soldout",
    name: "Agoda — Room Sold Out",
    brand: "Agoda",
    icon: "🚫",
    desc: "Room unavailable edge case",
    category: "edge",
    color: "#E31837",
    type: "error",
  },
  {
    id: "refund-flow",
    name: "Refund Request",
    brand: "Shopee",
    icon: "↩️",
    desc: "Return & refund process",
    category: "post",
    color: "#0284C7",
    type: "refund",
  },
  {
    id: "cancel-booking",
    name: "Cancel Booking",
    brand: "Airbnb",
    icon: "🚫",
    desc: "Cancellation & policy",
    category: "post",
    color: "#FF385C",
    type: "cancel",
  },
  {
    id: "show-receipt",
    name: "Show Receipt",
    brand: "Visa / GrabPay",
    icon: "🧾",
    desc: "Full receipt UI after payment",
    category: "post",
    color: "#5B4BF5",
    type: "receipt",
  },
  {
    id: "view-booking",
    name: "View Booking",
    brand: "Airbnb",
    icon: "🗓️",
    desc: "Booking details & itinerary",
    category: "post",
    color: "#FF385C",
    type: "booking",
  },
  {
    id: "duitnow-qr",
    name: "DuitNow QR",
    brand: "DuitNow",
    icon: "🔳",
    desc: "Scan QR · Malaysian real-time payment",
    category: "qr",
    color: "#E2231A",
    type: "qr",
  },
  {
    id: "duitnow-insufficient",
    name: "DuitNow — Low Balance",
    brand: "DuitNow",
    icon: "⚠️",
    desc: "Insufficient funds edge case",
    category: "qr",
    color: "#E2231A",
    type: "qr",
  },
  {
    id: "duitnow-error",
    name: "DuitNow — Payment Error",
    brand: "DuitNow",
    icon: "🔴",
    desc: "Timeout & system error edge case",
    category: "qr",
    color: "#E2231A",
    type: "qr",
  },
  {
    id: "crypto-pay",
    name: "Crypto Payment",
    brand: "BTC / ETH / USDT",
    icon: "₿",
    desc: "Pay with Bitcoin, Ethereum or USDT",
    category: "crypto",
    color: "#F7931A",
    type: "crypto",
  },
  {
    id: "crypto-receipt",
    name: "Crypto Receipt & Tx",
    brand: "Blockchain",
    icon: "🔗",
    desc: "On-chain confirmation & receipt",
    category: "post",
    color: "#627EEA",
    type: "crypto",
  },
  {
    id: "shopify-checkout",
    name: "Shopify Checkout",
    brand: "Shopify",
    icon: "🛒",
    desc: "E-commerce checkout with voucher",
    category: "ecommerce",
    color: "#96BF48",
    type: "checkout",
  },
  {
    id: "shopify-voucher-invalid",
    name: "Shopify — Invalid Voucher",
    brand: "Shopify",
    icon: "🚫",
    desc: "Expired / wrong voucher code",
    category: "ecommerce",
    color: "#96BF48",
    type: "checkout",
  },
];

export const CATEGORIES: Category[] = [
  { id: "all", label: "All Flows", icon: "◉" },
  { id: "digital", label: "Digital Pay", icon: "📱" },
  { id: "card", label: "Card", icon: "💳" },
  { id: "ecommerce", label: "E-Commerce", icon: "🛒" },
  { id: "booking", label: "Bookings", icon: "🏡" },
  { id: "paylater", label: "PayLater", icon: "⏰" },
  { id: "points", label: "Points", icon: "⭐" },
  { id: "rewards", label: "Rewards", icon: "🎁" },
  { id: "qr", label: "QR Payment", icon: "🔳" },
  { id: "crypto", label: "Crypto", icon: "₿" },
  { id: "edge", label: "Edge Cases", icon: "⚠️" },
  { id: "post", label: "Post-Payment", icon: "📋" },
];

export const FLOW_STEPS: FlowSteps = {
  "grabpay-wallet": [
    "Cart Review",
    "Select Method",
    "Confirm Amount",
    "Success",
  ],
  "apple-pay-bio": ["Checkout", "Face ID Auth", "Processing", "Confirmed"],
  "google-pay-card": ["Order Summary", "Google Pay", "Card Review", "Done"],
  "visa-card": ["Card Entry", "3DS OTP", "Processing", "Paid"],
  "airbnb-booking": ["Choose Dates", "Guest Details", "Payment", "Booked!"],
  "agoda-booking": [
    "Room Details",
    "Payment Method",
    "FPX Bank",
    "Processing",
    "Confirmed!",
  ],
  "agoda-soldout": ["Room Details", "Sold Out", "Find Similar"],
  "klook-booking": [
    "Activity Details",
    "Upgrades & Discounts",
    "Payment",
    "Processing",
    "Confirmed!",
  ],
  grabpoints: ["Cart", "Use Points", "Points Deducted", "Complete"],
  "shopee-coupon": ["Cart", "Apply Voucher", "Payment", "Order Placed"],
  "amazon-1click": ["Item Page", "1-Click Buy", "Processing", "Ordered!"],
  "pending-bank": ["FPX Bank", "Bank Portal", "Waiting...", "Confirmed"],
  "failed-decline": ["Card Entry", "Processing", "Declined!", "Try Again"],
  "offline-error": ["Cart", "No Signal", "Error", "Retry"],
  "refund-flow": ["Order", "Request Refund", "Processing", "Refunded"],
  "cancel-booking": ["Booking", "Cancel?", "Policy Check", "Cancelled"],
  "show-receipt": [
    "Payment Done",
    "View Receipt",
    "Receipt Detail",
    "Share / Save",
  ],
  "view-booking": [
    "Booking Confirmed",
    "Booking Detail",
    "Check-In Info",
    "Manage Booking",
  ],
  "duitnow-qr": ["Scan QR", "Verify Amount", "Authorise", "Success"],
  "duitnow-insufficient": [
    "Scan QR",
    "Verify Amount",
    "Authorise",
    "Insufficient Balance",
    "Retry",
  ],
  "duitnow-error": [
    "Scan QR",
    "Verify Amount",
    "Processing",
    "Timeout Error",
    "Retry",
  ],
  "crypto-pay": [
    "Select Coin",
    "Wallet & QR",
    "Send Payment",
    "Network Confirm",
    "Complete",
  ],
  "crypto-receipt": ["Tx Receipt", "Block Explorer", "Share Proof"],
  "shopify-checkout": [
    "Cart",
    "Information",
    "Shipping",
    "Payment & Voucher",
    "Confirmed",
  ],
  "shopify-voucher-invalid": [
    "Cart",
    "Information",
    "Payment & Voucher",
    "Invalid Code",
    "Fix & Pay",
  ],
};
